#!/usr/bin/env bash
set -Eeuo pipefail

APP_NAME="hermes-agent"
APP_DIR="/opt/hermes-agent"
REPO_URL="https://github.com/NousResearch/hermes-agent"
PM2_NAME="hermes-agent"
ROUTER_PM2_NAME="9router"
ROUTER_PORT="20128"

RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
BLUE="\033[0;34m"
CYAN="\033[0;36m"
BOLD="\033[1m"
NC="\033[0m"

trap 'echo -e "\n${RED}ERROR:${NC} Installer gagal di line $LINENO. Cek pesan error di atas."' ERR

banner() {
  clear || true
  echo -e "${CYAN}${BOLD}"
  cat <<'EOF'
=================================================
        HERMES AI AGENT INSTALLER
=================================================
EOF
  echo -e "${NC}"
}

step() {
  echo -e "\n${BLUE}${BOLD}[$1/10]${NC} $2"
}

info() { echo -e "${CYAN}INFO:${NC} $1"; }
ok() { echo -e "${GREEN}OK:${NC} $1"; }
warn() { echo -e "${YELLOW}WARNING:${NC} $1"; }
fail() { echo -e "${RED}ERROR:${NC} $1"; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1
}

as_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

ask_required() {
  local prompt="$1"
  local value=""
  while [[ -z "$value" ]]; do
    read -r -p "$prompt: " value
    if [[ -z "$value" ]]; then
      warn "Input tidak boleh kosong."
    fi
  done
  printf "%s" "$value"
}

ask_secret() {
  local prompt="$1"
  local value=""
  while [[ -z "$value" ]]; do
    read -r -s -p "$prompt: " value
    echo
    if [[ -z "$value" ]]; then
      warn "Input tidak boleh kosong."
    fi
  done
  printf "%s" "$value"
}

detect_pkg_manager() {
  if need_cmd apt; then
    echo "apt"
  else
    fail "Installer ini hanya mendukung Ubuntu/Debian dengan apt."
  fi
}

install_node() {
  if need_cmd node && node -v | grep -Eq '^v(20|22)\.'; then
    ok "Node.js sudah terinstall: $(node -v)"
    return
  fi

  info "Install Node.js LTS dari NodeSource..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | as_root bash -
  as_root apt-get install -y nodejs
  ok "Node.js: $(node -v), npm: $(npm -v)"
}

handle_existing_dir() {
  if [[ -d "$APP_DIR" ]]; then
    warn "Folder $APP_DIR sudah ada."
    echo "Pilih:"
    echo "  1) Reinstall / hapus folder lama"
    echo "  2) Backup folder lama lalu install ulang"
    echo "  3) Cancel"
    read -r -p "Pilihan [1/2/3]: " choice
    case "$choice" in
      1)
        as_root rm -rf "$APP_DIR"
        ok "Folder lama dihapus."
        ;;
      2)
        local backup="${APP_DIR}_backup_$(date +%Y%m%d_%H%M%S)"
        as_root mv "$APP_DIR" "$backup"
        ok "Folder lama dibackup ke $backup"
        ;;
      *)
        fail "Install dibatalkan."
        ;;
    esac
  fi
}

choose_provider() {
  echo
  echo "Pilih provider LLM:"
  echo "  1) Groq"
  echo "  2) OpenAI"
  echo "  3) Gemini"
  echo "  4) OpenRouter"
  echo "  5) NVIDIA"
  echo "  6) Kiro via 9Router"
  echo "  7) Custom OpenAI-compatible"
  read -r -p "Pilihan [1-7]: " provider

  case "$provider" in
    1)
      PROVIDER_NAME="Groq"
      DEFAULT_BASE_URL="https://api.groq.com/openai/v1"
      DEFAULT_MODEL="llama-3.1-8b-instant"
      ;;
    2)
      PROVIDER_NAME="OpenAI"
      DEFAULT_BASE_URL="https://api.openai.com/v1"
      DEFAULT_MODEL="gpt-4o-mini"
      ;;
    3)
      PROVIDER_NAME="Gemini"
      DEFAULT_BASE_URL="https://generativelanguage.googleapis.com/v1beta/openai/"
      DEFAULT_MODEL="gemini-2.5-flash"
      ;;
    4)
      PROVIDER_NAME="OpenRouter"
      DEFAULT_BASE_URL="https://openrouter.ai/api/v1"
      DEFAULT_MODEL="deepseek/deepseek-chat-v3.1:free"
      ;;
    5)
      PROVIDER_NAME="NVIDIA"
      DEFAULT_BASE_URL="https://integrate.api.nvidia.com/v1"
      DEFAULT_MODEL="meta/llama-3.1-8b-instruct"
      ;;
    6)
      PROVIDER_NAME="Kiro via 9Router"
      DEFAULT_BASE_URL="http://127.0.0.1:${ROUTER_PORT}/v1"
      DEFAULT_MODEL="kiro"
      ;;
    7)
      PROVIDER_NAME="Custom"
      DEFAULT_BASE_URL=""
      DEFAULT_MODEL=""
      ;;
    *)
      warn "Pilihan tidak valid, default ke Groq."
      PROVIDER_NAME="Groq"
      DEFAULT_BASE_URL="https://api.groq.com/openai/v1"
      DEFAULT_MODEL="llama-3.1-8b-instant"
      ;;
  esac
}

write_env() {
  local env_file="$APP_DIR/.env"

  if [[ -f "$env_file" ]]; then
    as_root cp "$env_file" "$env_file.backup.$(date +%Y%m%d_%H%M%S)"
    ok ".env lama dibackup."
  fi

  cat > /tmp/hermes.env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NODE_ENV=production
LOG_LEVEL=info

TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

OPENAI_API_KEY=${OPENAI_API_KEY}
OPENAI_BASE_URL=${OPENAI_BASE_URL}
MODEL=${MODEL}
EOF

  as_root mv /tmp/hermes.env "$env_file"
  as_root chown -R "$USER_TO_OWN:$USER_TO_OWN" "$APP_DIR" || true
  as_root chmod 600 "$env_file" || true
  ok "File .env dibuat di $env_file"
}

install_9router_if_needed() {
  if [[ "$PROVIDER_NAME" != "Kiro via 9Router" ]]; then
    return
  fi

  echo
  read -r -p "Install dan jalankan 9Router di VPS ini? [Y/n]: " install_router
  install_router="${install_router:-Y}"

  if [[ "$install_router" =~ ^[Yy]$ ]]; then
    info "Install 9Router..."
    as_root npm install -g 9router

    pm2 delete "$ROUTER_PM2_NAME" >/dev/null 2>&1 || true
    pm2 start "9router --host 127.0.0.1 --port ${ROUTER_PORT}" --name "$ROUTER_PM2_NAME"
    pm2 save
    ok "9Router jalan di http://127.0.0.1:${ROUTER_PORT}"
    warn "Buka dashboard 9Router dengan SSH tunnel:"
    echo "ssh -L ${ROUTER_PORT}:127.0.0.1:${ROUTER_PORT} user@IP_VPS"
    echo "Lalu buka http://127.0.0.1:${ROUTER_PORT} di browser."
  fi
}

test_api() {
  echo
  read -r -p "Test API sekarang? [y/N]: " do_test
  do_test="${do_test:-N}"
  if [[ ! "$do_test" =~ ^[Yy]$ ]]; then
    return
  fi

  info "Testing endpoint models..."
  set +e
  curl -sS "${OPENAI_BASE_URL%/}/models" \
    -H "Authorization: Bearer ${OPENAI_API_KEY}" \
    -H "Content-Type: application/json" | jq . || true
  set -e
}

start_pm2() {
  cd "$APP_DIR"

  pm2 delete "$PM2_NAME" >/dev/null 2>&1 || true

  if [[ -f "ecosystem.config.js" ]]; then
    info "Menjalankan Hermes dengan ecosystem.config.js..."
    pm2 start ecosystem.config.js --only "$PM2_NAME" || pm2 start ecosystem.config.js
  elif [[ -f "package.json" ]] && jq -e '.scripts.start' package.json >/dev/null 2>&1; then
    info "Menjalankan Hermes dengan npm start..."
    pm2 start npm --name "$PM2_NAME" -- start
  elif [[ -f "index.js" ]]; then
    info "Menjalankan Hermes dengan index.js..."
    pm2 start index.js --name "$PM2_NAME"
  else
    warn "Tidak menemukan entrypoint jelas. Coba cek dokumentasi repo Hermes."
    warn "Installer tetap selesai, tapi Hermes belum dijalankan."
    return
  fi

  pm2 save

  set +e
  startup_cmd="$(pm2 startup systemd -u "$USER_TO_OWN" --hp "$HOME_DIR" | tail -n 1)"
  set -e
  if echo "$startup_cmd" | grep -q "sudo"; then
    warn "Jika auto-start belum aktif, jalankan command yang ditampilkan PM2 di atas."
  fi

  ok "Hermes dijalankan via PM2."
}

main() {
  banner

  USER_TO_OWN="${SUDO_USER:-$(whoami)}"
  HOME_DIR="$(eval echo "~${USER_TO_OWN}")"

  step 1 "Cek sistem"
  detect_pkg_manager >/dev/null
  if ! grep -qi ubuntu /etc/os-release; then
    warn "OS bukan Ubuntu. Installer tetap mencoba lanjut."
  fi

  step 2 "Update system"
  as_root apt-get update -y
  as_root apt-get upgrade -y

  step 3 "Install dependency dasar"
  as_root apt-get install -y curl git build-essential unzip jq ca-certificates gnupg

  step 4 "Install Node.js LTS dan PM2"
  install_node
  as_root npm install -g pm2
  ok "PM2: $(pm2 -v)"

  step 5 "Siapkan folder install"
  handle_existing_dir
  as_root mkdir -p "$(dirname "$APP_DIR")"
  as_root chown -R "$USER_TO_OWN:$USER_TO_OWN" "$(dirname "$APP_DIR")" || true

  step 6 "Clone Hermes Agent"
  git clone "$REPO_URL" "$APP_DIR"
  as_root chown -R "$USER_TO_OWN:$USER_TO_OWN" "$APP_DIR" || true

  step 7 "Input konfigurasi"
  TELEGRAM_BOT_TOKEN="$(ask_required "Masukkan Telegram Bot Token")"
  TELEGRAM_CHAT_ID="$(ask_required "Masukkan Telegram Chat ID")"

  choose_provider

  if [[ "$PROVIDER_NAME" == "Kiro via 9Router" ]]; then
    OPENAI_API_KEY="test"
  else
    OPENAI_API_KEY="$(ask_secret "Masukkan API Key ${PROVIDER_NAME}")"
  fi

  if [[ -n "$DEFAULT_BASE_URL" ]]; then
    read -r -p "Base URL [${DEFAULT_BASE_URL}]: " OPENAI_BASE_URL
    OPENAI_BASE_URL="${OPENAI_BASE_URL:-$DEFAULT_BASE_URL}"
  else
    OPENAI_BASE_URL="$(ask_required "Masukkan Base URL")"
  fi

  if [[ -n "$DEFAULT_MODEL" ]]; then
    read -r -p "Model [${DEFAULT_MODEL}]: " MODEL
    MODEL="${MODEL:-$DEFAULT_MODEL}"
  else
    MODEL="$(ask_required "Masukkan Model name")"
  fi

  [[ -z "$OPENAI_BASE_URL" ]] && fail "OPENAI_BASE_URL kosong."
  [[ -z "$MODEL" ]] && fail "MODEL kosong."

  step 8 "Install 9Router jika diperlukan"
  install_9router_if_needed

  step 9 "Buat .env dan install npm dependencies"
  write_env
  cd "$APP_DIR"

  if [[ -f "package-lock.json" ]]; then
    npm ci || npm install
  else
    npm install
  fi

  test_api

  step 10 "Jalankan Hermes dengan PM2"
  start_pm2

  echo
  echo -e "${GREEN}${BOLD}INSTALL SELESAI.${NC}"
  echo
  echo "Command penting:"
  echo "  pm2 status"
  echo "  pm2 logs ${PM2_NAME}"
  echo "  pm2 restart ${PM2_NAME}"
  echo "  pm2 stop ${PM2_NAME}"
  echo "  nano ${APP_DIR}/.env"
  echo
  echo "Provider: ${PROVIDER_NAME}"
  echo "Base URL: ${OPENAI_BASE_URL}"
  echo "Model: ${MODEL}"
  echo "API Key: ********"
  echo
  warn "Jika Telegram belum membalas, cek: pm2 logs ${PM2_NAME}"
}

main "$@"
